Repository wordpress-mobile/GutenbergKit, pull requests merged in 2024-11, with the labels that each got.

#30 Add Android Request Interception
  Demo-Android/Gutenberg/build.gradle.kts
  Demo-Android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergRequestInterceptor.kt
  Demo-Android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt
Labels: bug

#35 feat: Media Library support (iOS)
  ReactApp/src/components/Editor.jsx
  ReactApp/src/components/hooks/use-media-upload.js
  ReactApp/src/misc/Helpers.js
  Sources/GutenbergKit/Gutenberg/assets/App-8sifGnV4.js
  Sources/GutenbergKit/Gutenberg/assets/App-CODBWdK9.js
  Sources/GutenbergKit/Gutenberg/assets/index-B5BKfeGd.css
  Sources/GutenbergKit/Gutenberg/assets/index-BH-0YKBm.js
  Sources/GutenbergKit/Gutenberg/assets/index-RZTgLxeV.js
  Sources/GutenbergKit/Gutenberg/assets/index-U9U0j6Xt.css
  Sources/GutenbergKit/Gutenberg/assets/remote-Dw1d-ref.js
  Sources/GutenbergKit/Gutenberg/assets/remote-rwu8cmU5.js
  Sources/GutenbergKit/Gutenberg/index.html
  Sources/GutenbergKit/Gutenberg/remote.html
  Sources/GutenbergKit/Sources/EditorJSMessage.swift
  Sources/GutenbergKit/Sources/EditorTypes.swift
  Sources/GutenbergKit/Sources/EditorViewController.swift
  Sources/GutenbergKit/Sources/EditorViewControllerDelegate.swift
Labels: enhancement

#40 Add ESLint in CI
  .buildkite/pipeline.yml
Labels: enhancement

#41 docs: Expand inline documentation
  src/components/app.jsx
  src/components/editor-load-notice.jsx
  src/components/editor-toolbar.jsx
  src/components/editor.jsx
  src/hooks/use-editor-styles.js
  src/hooks/use-media-upload.js
  src/index.jsx
  src/remote.jsx
  src/utils/api-fetch-setup.js
  src/utils/bridge.js
Labels: documentation

#43 docs: Add GitHub templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation

#44 docs: Fix GitHub template
  .github/ISSUE_TEMPLATE/bug.md
Labels: documentation
