Repository wordpress-mobile/GutenbergKit, pull requests merged in 2024-12, with the labels that each got.

#47 docs: Refine GitHub template
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .prettierignore
Labels: documentation

#46 fix: Remove duplicative iOS content decoding
  ios/Sources/GutenbergKit/Sources/EditorViewController.swift
Labels: bug

#48 feat: Open editor canvas links
  android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt
  ios/Sources/GutenbergKit/Sources/EditorViewController.swift
Labels: enhancement

#49 refactor: Editor leverages environment variables
  README.md
  android/Gutenberg/build.gradle.kts
  android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt
  android/build.gradle.kts
  docs/example-xcode-env-variable.png
  docs/gutenberg-kit-preview.png
  ios/Demo-iOS/Sources/ContentView.swift
  ios/Demo-iOS/Sources/EditorView.swift
Labels: enhancement

#50 fix: Replace unsupported editor architecture
  android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt
  package-lock.json
  package.json
  patches/@wordpress+editor+14.10.0.patch
  patches/README.md
  src/components/editor.jsx
Labels: bug

#51 Update demo instructions
  README.md
Labels: documentation

#52 fix: Address disruptive UI bugs
  package-lock.json
  package.json
  src/components/app.jsx
  src/components/editor-interface/index.jsx
  src/components/editor-interface/style.scss
  src/components/editor-load-notice.jsx
  src/components/editor-toolbar/index.jsx
  src/components/editor-toolbar/style.scss
  src/components/editor/index.jsx
  src/components/editor/style.scss
  src/hooks/default-theme-styles.scss
  src/hooks/use-editor-styles.js
  src/index.html
  src/index.jsx
  src/index.scss
  src/remote.html
  src/remote.jsx
  src/utils/api-fetch-setup.js
  vite.config.js
  vite.config.remote.js
Labels: bug
