Repository wordpress-mobile/GutenbergKit, pull requests merged in 2025-07, with the labels that each got.

#144 Add cookie support
  android/Gutenberg/src/main/java/org/wordpress/gutenberg/EditorConfiguration.kt
  android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt
  android/app/src/main/java/com/example/gutenbergkit/MainActivity.kt
  ios/Demo-iOS/Sources/EditorView.swift
  ios/Sources/GutenbergKit/Sources/EditorConfiguration.swift
  ios/Sources/GutenbergKit/Sources/EditorViewController.swift
Labels: [Type] Enhancement

#157 feat: Remove iOS cookie configuration
  ios/Sources/GutenbergKit/Sources/EditorConfiguration.swift
  ios/Sources/GutenbergKit/Sources/EditorViewController.swift
Labels: [Type] Task

#159 fix: Prevent iOS crash in WebView navigations
  ios/Sources/GutenbergKit/Sources/EditorViewController.swift
Labels: [Type] Bug
