Repository wordpress-mobile/GutenbergKit, pull requests merged in 2025-02, with the labels that each got.

#70 fix: Gradient background error
  package-lock.json
  package.json
Labels: bug

#73 docs: Fix README.md typo
  README.md
Labels: documentation

#80 fix: Catch null content errors
  android/Gutenberg/src/main/java/org/wordpress/gutenberg/GutenbergView.kt
Labels: bug

#83 task: Update issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: [Type] Task

#95 fix: Prevent sized images overflow
  src/components/visual-editor/style.scss
  src/index.html
  src/index.scss
  src/remote.html
Labels: [Type] Bug

#96 fix: Prevent unsupported block overflow
  src/components/visual-editor/style.scss
Labels: [Type] Bug

#92 [Build] Update Gradle to 8.12.1 and AGP to 8.8.1
  android/gradle/libs.versions.toml
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
Labels: [Type] Build Tooling

#100 fix: Allow copying content on error
  src/components/layout.jsx
Labels: [Type] Bug

#101 build: Format with wp-prettier
  .eslintrc.cjs
  .prettierrc.cjs
  package-lock.json
  package.json
  src/components/default-block-appender/index.jsx
  src/components/editor-load-notice.jsx
  src/components/editor-toolbar/index.jsx
  src/components/editor/index.jsx
  src/components/editor/style.scss
  src/components/editor/use-editor-setup.js
  src/components/editor/use-gbkit-settings.js
  src/components/editor/use-host-bridge.js
  src/components/editor/use-host-exception-logging.js
  src/components/editor/use-media-upload.js
  src/components/editor/use-sync-history-controls.js
  src/components/layout/index.jsx
  src/components/layout/style.scss
  src/components/text-editor/index.jsx
  src/components/visual-editor/index.jsx
  src/components/visual-editor/use-editor-styles.js
  src/index.jsx
  src/remote.jsx
  src/utils/api-fetch-setup.js
  src/utils/bridge.js
  src/utils/parse-exception.js
  src/utils/post-type-entities.js
  src/utils/stack-parsers.js
  vite.config.js
  vite.config.remote.js
Labels: [Type] Task
